Llelievr/battery shield defaults
SlimeVR/SlimeVR-Firmware-WebBuilder pull request #19
Opened 2023-08-03 20:21 UTC by loucass003

Closes #12

@unlogisch04 you can check this file to see the defaults values on each boards. I wont ask you to review the code ;) but please double check those defaults for me 🙏

2023-08-03 23:08 UTC, unlogisch04 requested changes
I think it was good that i did look over it.

In the defines.h for some boards the LED is disabled by default, and falls back to the board. If the board defines a LED it will use the onboard led. But for that the ´#define LED_PIN´ should not be in the file.

2023-08-03 23:08 UTC, unlogisch04 commented on backend/src/firmware/boards-infos.json
> +            "led": "2",
`//  #define LED_PIN 2`
Is commented out. That will look for "LED_BUILTIN" in <globals.h>
so it would be needed to leave blank (no entry)

2023-08-03 23:08 UTC, unlogisch04 commented on backend/src/firmware/boards-infos.json
> +            "led": "2",
`//  #define LED_PIN 2`
Is commented out. That will look for "LED_BUILTIN" in <globals.h>
so it would be needed to leave blank (no entry)
For the D1 mini LED_BUILTIN will probably be 2

2023-08-03 23:08 UTC, unlogisch04 commented on backend/src/firmware/boards-infos.json
> +            "ledInverted": false,
```suggestion
            "ledInverted": true,
```
`//  #define LED_INVERTED true`
In <defines.h> this is not defined -> default from <globals.h>
is ledInverted true

2023-08-03 23:08 UTC, unlogisch04 commented on backend/src/firmware/boards-infos.json
> +            "ledInverted": false,
```suggestion
            "ledInverted": true,
```
`//  #define LED_INVERTED true`
In <defines.h> this is not defined -> default from <globals.h> 
is ledInverted true

2023-08-03 23:08 UTC, unlogisch04 commented on backend/src/firmware/boards-infos.json
> +            "imuSCL": "5",
```suggestion
            "imuSDA": "5",
            "imuSCL": "4",
```
<defines.h> line 140 and 141

2023-08-03 23:08 UTC, unlogisch04 commented on backend/src/firmware/boards-infos.json
> +            "led": "2",
`//  #define LED_PIN 2`
Is commented out. That will look for "LED_BUILTIN" in <globals.h>
so it would be needed to leave blank (no entry)
For the TTGO it should be LED_BUILTIN will probably be 2

2023-08-03 23:08 UTC, unlogisch04 commented on backend/src/firmware/boards-infos.json
> +            "imuSCL": "0",
```suggestion
            "imuSDA": "21",
            "imuSCL": "22",
```
<defines.h> line 150 151

2023-08-03 23:08 UTC, unlogisch04 commented on backend/src/firmware/boards-infos.json
> +            "led": "2",
`//  #define LED_PIN 2`
Is commented out. That will look for "LED_BUILTIN" in <globals.h>
so it would be needed to leave blank (no entry)
WROOM is the module i dont think it has ifself a LED

2023-08-03 23:08 UTC, unlogisch04 commented on backend/src/firmware/boards-infos.json
> +            "ledInverted": false,
`//  #define LED_INVERTED false`
In <defines.h> this is not defined -> default from <globals.h>
is ledInverted true

2023-08-03 23:08 UTC, unlogisch04 commented on backend/src/firmware/boards-infos.json
> +            "batteryPin": "A0",
```suggestion
            "batteryPin": "255",
```
https://github.com/SlimeVR/SlimeVR-Tracker-ESP/blob/main/src/defines.h#L136

2023-08-15 18:05 UTC, loucass003 commented
Closing that PR, Making a bigger one with some big rewrites

2023-08-15 18:05 UTC, closed without merging