Add compatibility with multi-sensor/glove/v0.6.0 firmware
SlimeVR/SlimeVR-Firmware-WebBuilder pull request #24
Opened 2024-12-19 18:36 UTC by Eirenliel

This PR adds generating defines compatibility for https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/371 This doesn't actually implement any new functionality (like additional i2c pins or more than 2 IMUs etc)

2025-01-06 14:14 UTC, loucass003 requested changes

2025-01-06 14:14 UTC, loucass003 commented on src/firmware/firmwares.json
> +  "Multi-sensor/Glove": {
This should be inside the SlimeVR section at the top of the file, the ``{  "OWNER": { "REPO": ["BRANCH", "BRANCH2"] } }``

2025-02-15 15:02 UTC, Eirenliel commented
can you fix plz @loucass003 🥺 🙏

2025-02-15 15:08 UTC, unlogisch04 commented
Im missing `#define TRACKER_TYPE 0` for it to build.

2025-02-16 11:50 UTC, unlogisch04 requested changes

2025-02-16 11:50 UTC, unlogisch04 commented on src/firmware/firmware-builder.service.ts
> +          #define MAX_SENSORS_COUNT ${imusConfig.length}
```suggestion
          #define MAX_SENSORS_COUNT ${imusConfig.length}
          // Make sure the Tracker is defined as Rotating (TrackerType::TRACKER_TYPE_SVR_ROTATION) 
          // (will need to be changed for glove left / right) Static number to support older FW Builds
          #define TRACKER_TYPE 0
```

2025-02-18 17:33 UTC, merged